# Generated by Django 5.2.3 on 2025-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_file_access_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "permissions": [
                    ("can_view_ticket", "Can view ticket"),
                    ("can_resolve_ticket", "Can resolve ticket"),
                ]
            },
        ),
        migrations.AddField(
            model_name="filecategory",
            name="icon",
            field=models.CharField(default="default_icon", max_length=255),
        ),
    ]
