# Generated by Django 5.2.3 on 2025-07-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_ticket_options_filecategory_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zone",
            name="region",
        ),
    ]
