# Generated by Django 5.2.3 on 2025-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_rename_comment_ticketcomment_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=20)),
                ("slug", models.SlugField(blank=True)),
            ],
        ),
    ]
