# Generated by Django 5.2.3 on 2025-07-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_ticketstatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TicketStatus",
        ),
    ]
