# Generated by Django 5.2.3 on 2025-07-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_delete_ticketstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("confidential", "Confidential"),
                    ("restricted", "Restricted"),
                    ("public", "Public"),
                ],
                default="restricted",
                max_length=20,
            ),
        ),
    ]
