# Generated by Django 5.2.3 on 2025-07-21 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_file_access_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="authorized_users",
            field=models.ManyToManyField(
                blank=True, related_name="authorized_files", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
