# Generated by Django 5.2.3 on 2025-07-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_ticket_responsible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminal",
            name="region",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.region"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="terminal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.terminal",
            ),
        ),
    ]
