# Generated by Django 5.2.3 on 2025-07-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_terminal_region_alter_ticket_terminal"),
    ]

    operations = [
        migrations.AddField(
            model_name="versioncontrol",
            name="app_version",
            field=models.CharField(default="1.0.0", max_length=100),
        ),
        migrations.AddField(
            model_name="versioncontrol",
            name="ejournal",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="versioncontrol",
            name="responsible",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="versioncontrol",
            name="xfs",
            field=models.CharField(default="N/A", max_length=100),
        ),
    ]
