# Generated by Django 5.2.3 on 2025-07-23 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_versioncomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.customer",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.region",
            ),
        ),
    ]
