# Generated by Django 5.2.3 on 2025-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_ticket_resolved_at_ticket_resolved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="status_color",
            field=models.CharField(default="green", max_length=20),
        ),
    ]
