# Generated by Django 5.2.3 on 2025-07-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_ticket_status_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="status_color",
        ),
    ]
