# Generated by Django 5.2.3 on 2025-07-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_remove_ticket_status_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.customer",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.region",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.terminal",
            ),
        ),
    ]
