# Generated by Django 5.2.3 on 2025-07-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_ticket_customer_alter_ticket_region"),
    ]

    operations = []
