# Generated by Django 5.2.3 on 2025-07-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_auto_20250725_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.customer"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.region"
            ),
        ),
    ]
