# Generated by Django 5.2.3 on 2025-07-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_ticket_customer_alter_ticket_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="resolution",
            field=models.TextField(blank=True, null=True),
        ),
    ]
