# Generated by Django 5.2.3 on 2025-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_remove_ticket_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="title",
            field=models.CharField(default="Issue", max_length=255),
        ),
    ]
