# Generated by Django 5.2.3 on 2025-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_ticket_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
