# Generated by Django 5.2.3 on 2025-07-31 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_customer_custodian_customer_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="manager",
        ),
        migrations.AddField(
            model_name="customer",
            name="overseer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overseeing_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
