# Generated by Django 5.2.3 on 2025-08-01 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_remove_customer_manager_customer_overseer"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.customer",
            ),
        ),
    ]
