# Generated by Django 5.2.3 on 2025-08-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_profile_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.terminal",
            ),
        ),
    ]
