# Generated by Django 5.2.3 on 2025-08-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_profile_terminal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminal",
            name="serial_number",
            field=models.CharField(default="SN0000", max_length=100),
        ),
    ]
