# Generated by Django 5.2.3 on 2025-08-05 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_terminal_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminal",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terminals",
                to="core.customer",
            ),
        ),
    ]
