# Generated by Django 5.2.3 on 2025-08-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_terminal_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminal",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.customer",
            ),
        ),
    ]
