# Generated by Django 5.2.3 on 2025-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_terminal_custodian"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versioncontrol",
            name="responsible",
        ),
        migrations.AddField(
            model_name="versioncontrol",
            name="brits",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="versioncontrol",
            name="neo_atm",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="versioncontrol",
            name="app_version",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="versioncontrol",
            name="ejournal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="versioncontrol",
            name="manufacturer",
            field=models.CharField(
                choices=[("GRG Banking", "GRG Banking"), ("Hitachi", "Hitachi")],
                default="GRG Banking",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="versioncontrol",
            name="xfs",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
