# Generated by Django 5.2.3 on 2025-08-08 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_remove_versioncontrol_responsible_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="current_escalation_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tier 1", "Tier 1"),
                    ("Tier 2", "Tier 2"),
                    ("Tier 3", "Tier 3"),
                    ("Tier 4", "Tier 4"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="escalated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalated_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="escalation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_escalated",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EscalationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Tier 1", "Tier 1"),
                            ("Tier 2", "Tier 2"),
                            ("Tier 3", "Tier 3"),
                            ("Tier 4", "Tier 4"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_level",
                    models.CharField(
                        choices=[
                            ("Tier 1", "Tier 1"),
                            ("Tier 2", "Tier 2"),
                            ("Tier 3", "Tier 3"),
                            ("Tier 4", "Tier 4"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "escalated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_history",
                        to="core.ticket",
                    ),
                ),
            ],
        ),
    ]
