# Generated by Django 5.2.3 on 2025-08-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_ticket_current_escalation_level_ticket_escalated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminal",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
