# Generated by Django 5.2.3 on 2025-08-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_ticket_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
