# Generated by Django 5.2.3 on 2025-08-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_profile_id_number_profile_phone_number_profile_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="passcode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
