# Generated by Django 5.2.3 on 2025-08-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_file_access_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileaccesslog",
            name="action",
            field=models.CharField(
                choices=[("preview", "Preview"), ("download", "Download")],
                max_length=50,
                null=True,
            ),
        ),
    ]
