# Generated by Django 5.2.3 on 2025-08-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_alter_ticket_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="allow_download",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="file",
            name="allow_preview",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="passcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
