# Generated by Django 5.2.3 on 2025-08-22 09:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_file_allow_download_file_allow_preview_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="problemcategory",
            name="brts_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.unit",
            ),
        ),
        migrations.AlterField(
            model_name="problemcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("Hardware Related", "Hardware Related"),
                    ("Software Related", "Software Related"),
                    ("Cash Reconciliation", "Cash Reconciliation"),
                    ("Power and Network", "Power and Network"),
                    ("De-/Installation /Maintenance", "De-/Installation /Maintenance"),
                    ("Safe", "Safe"),
                    ("SLA Related", "SLA Related"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(default="Unknown Issue", max_length=255),
        ),
    ]
