# Generated by Django 5.2.3 on 2025-08-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="escalation_action",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="escalation_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
