# Generated by Django 5.2.5 on 2025-08-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_ticket_escalation_action_ticket_escalation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zone'),
        ),
    ]
