# Generated by Django 5.2.5 on 2025-09-01 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usernotification',
            constraint=models.UniqueConstraint(fields=('user', 'ticket'), name='unique_user_ticket_notification'),
        ),
    ]
