CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(50) UNIQUE,
  "password" varchar(255),
  "first_name" varchar(20),
  "last_name" varchar(20),
  "phone" varchar(15),
  "is_admin" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "visitors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(20),
  "last_name" varchar(20),
  "email" varchar(50) UNIQUE,
  "phone" varchar(15),
  "issue_type" varchar(50),
  "photo" blob,
  "redirect_to" varchar(255),
  "created_at" timestamp,
  "updated_at" timestamp
);
